%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/sinan/Dropbox/Research/Sabanci/Research Sabanci/Secim/secim datasi/Goc/Goc datasi/Goc_new.xlsx
%    Worksheet: Sheet0
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2019/10/09 13:51:50

%% Import the data
[~, ~, raw] = xlsread('Goc_new.xlsx','Sheet0');
raw = raw(2:end,:);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
Goc = reshape([raw{:}],size(raw));

%% Clear temporary variables
clearvars raw R;

Goc = (reshape(Goc(:, 3:end)', [81, 81, 11]));
Goc_years = 2008:2018;