function [GDP, GDP_years] = import_gdp

%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /GDP.xlsx
%    Worksheet: Sheet0
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2019/10/09 14:28:03

%% Import the data
[~, ~, raw] = xlsread('Datafiles/GDP.xlsx','Sheet0');
raw = raw(2:1135,end);

%% Create output variable
GDP = reshape([raw{:}],size(raw));


%% Clear temporary variables
clearvars raw;

GDP = reshape(GDP, 81, 14);
GDP_years = 2004:2017;
