function [Correlations, Correlations_years] = import_correlations

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: Datafiles/Correlations.csv
%
% Auto-generated by MATLAB on 28-May-2020 18:55:04

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 84);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Adana1", "Adiyaman2", "Afyonkarahisar3", "Agri4", "Aksaray68", "Amasya5", "Ankara6", "Antalya7", "Ardahan75", "Artvin8", "Aydin9", "Balikesir10", "Bartin74", "Batman72", "Bayburt69", "Bilecik11", "Bingl12", "Bitlis13", "Bolu14", "Burdur15", "Bursa16", "anakkale17", "ankiri18", "orum19", "Denizli20", "Diyarbakir21", "Dzce81", "Edirne22", "Elazig23", "Erzincan24", "Erzurum25", "Eskisehir26", "Gaziantep27", "Giresun28", "Gmshane29", "Hakkari30", "Hatay31", "Igdir76", "Isparta32", "Istanbul34", "Izmir35", "Kahramanmaras46", "Karabk78", "Karaman70", "Kars36", "Kastamonu37", "Kayseri38", "Kilis79", "Kirikkale71", "Kirklareli39", "Kirsehir40", "Kocaeli41", "Konya42", "Ktahya43", "Malatya44", "Manisa45", "Mardin47", "Mersin33", "Mugla48", "Mus49", "Nevsehir50", "Nigde51", "Ordu52", "Osmaniye80", "Rize53", "Sakarya54", "Samsun55", "Sanliurfa63", "Siirt56", "Sinop57", "Sirnak73", "Sivas58", "Tekirdag59", "Tokat60", "Trabzon61", "Tunceli62", "Usak64", "Van65", "Yalova77", "Yozgat66", "Zonguldak67"];
opts.SelectedVariableNames = ["Adana1", "Adiyaman2", "Afyonkarahisar3", "Agri4", "Aksaray68", "Amasya5", "Ankara6", "Antalya7", "Ardahan75", "Artvin8", "Aydin9", "Balikesir10", "Bartin74", "Batman72", "Bayburt69", "Bilecik11", "Bingl12", "Bitlis13", "Bolu14", "Burdur15", "Bursa16", "anakkale17", "ankiri18", "orum19", "Denizli20", "Diyarbakir21", "Dzce81", "Edirne22", "Elazig23", "Erzincan24", "Erzurum25", "Eskisehir26", "Gaziantep27", "Giresun28", "Gmshane29", "Hakkari30", "Hatay31", "Igdir76", "Isparta32", "Istanbul34", "Izmir35", "Kahramanmaras46", "Karabk78", "Karaman70", "Kars36", "Kastamonu37", "Kayseri38", "Kilis79", "Kirikkale71", "Kirklareli39", "Kirsehir40", "Kocaeli41", "Konya42", "Ktahya43", "Malatya44", "Manisa45", "Mardin47", "Mersin33", "Mugla48", "Mus49", "Nevsehir50", "Nigde51", "Ordu52", "Osmaniye80", "Rize53", "Sakarya54", "Samsun55", "Sanliurfa63", "Siirt56", "Sinop57", "Sirnak73", "Sivas58", "Tekirdag59", "Tokat60", "Trabzon61", "Tunceli62", "Usak64", "Van65", "Yalova77", "Yozgat66", "Zonguldak67"];
opts.VariableTypes = ["string", "string", "string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3"], "EmptyFieldRule", "auto");

% Import the data
Correlations = readtable("Datafiles/Correlations.csv", opts);

%% Convert to output type
Correlations = table2array(Correlations);
Correlations = (reshape(Correlations', [81, 81, 12]));

Correlations_years = 2008:2019;

%% Clear temporary variables
clear opts