function [Migration, Migration_years] = import_migration

%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Migration.xlsx
%    Worksheet: Sheet0
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2019/10/09 13:51:50

%% Import the data
[~, ~, raw] = xlsread('Datafiles/Migration.xlsx','Sheet0');
raw = raw(2:end,:);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
Migration = reshape([raw{:}],size(raw));

%% Clear temporary variables
clearvars raw R;

Migration = (reshape(Migration(:, 3:end)', [81, 81, 11]));
Migration_years = 2008:2018;