%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/sinan/Dropbox/Research/Sabanci/Research Sabanci/Secim/secim datasi/Goc/Goc datasi/issizlik_2014_2019.xlsx
%    Worksheet: Sheet0
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2020/05/12 16:58:51

%% Import the data
[~, ~, raw] = xlsread('/Users/sinan/Dropbox/Research/Sabanci/Research Sabanci/Secim/secim datasi/Goc/Goc datasi/issizlik_2014_2019.xlsx','Sheet0');
raw = raw(5:10,4:29);

%% Create output variable
issizlik20142019 = reshape([raw{:}],size(raw));

load('bolge_adlari2');

bolge_adlari_1_to_2 =[24, 20, 6, 25, 4, 17, 7, 13, 2, 14, 3, 1, 10, 15,...
    12, 23, 11, 19, 21, 8, 5, 16, 22, 9, 26, 18];

issizlik20142019 = issizlik20142019(:, bolge_adlari_1_to_2);

%% Clear temporary variables
clearvars raw;