%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/sinan/Dropbox/Research/Sabanci/Research Sabanci/Secim/secim datasi/Goc/Goc datasi/issizlik_orani_2004_2013.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2020/05/11 22:28:31

%% Import the data
[~, ~, raw] = xlsread('/Users/sinan/Dropbox/Research/Sabanci/Research Sabanci/Secim/secim datasi/Goc/Goc datasi/issizlik_2004_2013_oranlar.xlsx','Sheet1');
raw = raw(7:end,:);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
issizlik_2004_2013_oranlar = reshape([raw{:}],size(raw));

x = 1:12:301;
y = x + 9;
A = zeros(10, length(x));
for i = 1:length(x)
    A(:, i) = x(i):y(i);
end
a = A(:);

issizlik_2004_2013_oranlar = issizlik_2004_2013_oranlar(a, 2:end);

%% Clear temporary variables
clearvars raw R;