%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/sinan/Dropbox/Research/Sabanci/Research Sabanci/Secim/secim datasi/Goc/Goc datasi/Goc_all.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2019/10/09 14:41:35

%% Import the data
[~, ~, raw] = xlsread('Goc_all.xlsx','Sheet1');
raw = raw(164:892,35);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
Girisim = reshape([raw{:}],size(raw));

%% Clear temporary variables
clearvars raw R;

Girisim = reshape(Girisim, 81, 9);
Girisim_years = 2009:2017;