%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/sinan/Dropbox/Research/Sabanci/Research Sabanci/Secim/secim datasi/Goc/Goc datasi/istihdam_sayilari_2004_2013.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2020/05/12 09:23:17

%% Import the data
[~, ~, raw] = xlsread('/Users/sinan/Dropbox/Research/Sabanci/Research Sabanci/Secim/secim datasi/Goc/Goc datasi/istihdam_2004_2013_sayilar.xlsx','Sheet1');
raw = raw(9:end,2:7);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
istihdam_2004_2013_sayilar = reshape([raw{:}],size(raw));

x = 1:29:262;
y = x + 25;
A = zeros(26, length(x));
for i = 1:length(x)
    A(:, i) = x(i):y(i);
end
a = A(:);

istihdam_2004_2013_sayilar = istihdam_2004_2013_sayilar(a, :);

%% Clear temporary variables
clearvars raw R;