%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/sinan/Dropbox/Research/Sabanci/Research Sabanci/Secim/secim datasi/Goc/Goc datasi/isgucu_genel_2004_2013.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2020/05/12 11:16:52

%% Import the data
[~, ~, raw] = xlsread('isgucu_genel_2004_2013.xlsx','Sheet1');
raw = raw(10:end,1:14);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
isgucugenel20042013 = reshape([raw{:}],size(raw));

x = fliplr(1:30:271);
y = x + 25;

A = zeros(26, length(x));
for i = 1:length(x)
    A(:, i) = x(i):y(i);
end
a = A(:);

isgucugenel20042013 = isgucugenel20042013(a, 2:end);

K = {'Kurumsal olmayan calisma cagindaki nufus', 'Isgucu',...
    'Istihdam edilenler', 'Eksik istihdam',	'Zamana bagli eksik istihdam',...
    'Yetersiz istihdam', 'Issiz', 'Isg?c?ne katilma orani', ...
    'Issizlik orani', 'Tar?m disi i?sizlik orani', '?stihdam orani', ...
    'Eksik istihdamda olanlar?n i?g?c?ne orani', ...
    'Isg?c?ne dahil olmayan nufus'};

%% Clear temporary variables
clearvars raw R x y A a i;


%% Import the data
[~, ~, raw] = xlsread('issizlik_2014_2019.xlsx','Sheet0');
raw = raw(5:10,4:29);

%% Create output variable
issizlik20142019 = reshape([raw{:}],size(raw));

bolge_adlari_1_to_2 =[24, 20, 6, 25, 4, 17, 7, 13, 2, 14, 3, 1, 10, 15,...
    12, 23, 11, 19, 21, 8, 5, 16, 22, 9, 26, 18];

issizlik20142019 = issizlik20142019(:, bolge_adlari_1_to_2);

%% Clear temporary variables
clearvars raw;

Issizlik_1 = reshape(isgucugenel20042013(:, 9), 26, 10);
Issizlik_2 = issizlik20142019';

Issizlik = [Issizlik_1 Issizlik_2];
Issizlik_years = 2004:2019;

clear Issizlik_1 Issizlik_2 isgucugenel20042013 issizlik20142019;

conversions;

Issizlik_iller = Issizlik(Il_abc_2_Duzey, :);
clear Duzey_2_Il_abc Duzey_isim Il_plaka_2_Duzey bolge_ adlari ...
    bolge_adlari2 bolge_adlari_1_to_2 il_abc_2_plaka il_plaka_2_abc ...
    ilmesafe_abc_abc ilmesafe_plaka_plaka Il_abc_2_Duzey;