%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/sinan/Dropbox/Research/Sabanci/Research Sabanci/Secim/secim datasi/Goc/Goc datasi/isgucu_genel_2004_2013.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2020/05/12 11:16:52

%% Import the data
[~, ~, raw] = xlsread('/Users/sinan/Dropbox/Research/Sabanci/Research Sabanci/Secim/secim datasi/Goc/Goc datasi/isgucu_genel_2004_2013.xlsx','Sheet1');
raw = raw(10:end,1:14);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
isgucugenel20042013 = reshape([raw{:}],size(raw));

x = fliplr(1:30:271);
y = x + 25;

A = zeros(26, length(x));
for i = 1:length(x)
    A(:, i) = x(i):y(i);
end
a = A(:);

isgucugenel20042013 = isgucugenel20042013(a, 2:end);

K = {'Kurumsal olmayan calisma cagindaki nufus', 'Isgucu',...
    'Istihdam edilenler', 'Eksik istihdam',	'Zamana bagli eksik istihdam',...
    'Yetersiz istihdam', 'Issiz', 'Isg?c?ne katilma orani', ...
    'Issizlik orani', 'Tar?m disi i?sizlik orani', '?stihdam orani', ...
    'Eksik istihdamda olanlar?n i?g?c?ne orani', ...
    'Isg?c?ne dahil olmayan nufus'};

%% Clear temporary variables
clearvars raw R x y A a i;
