%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/sinan/Dropbox/Research/Sabanci/Research Sabanci/Secim/secim datasi/Goc/Goc datasi/GSYH.xlsx
%    Worksheet: Sheet0
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2019/10/09 14:28:03

%% Import the data
[~, ~, raw] = xlsread('GSYH.xlsx','Sheet0');
raw = raw(2:1135,end);

%% Create output variable
GSYH = reshape([raw{:}],size(raw));


%% Clear temporary variables
clearvars raw;

GSYH = reshape(GSYH, 81, 14);
GSYH_years = 2004:2017;
