function [Kurd] = import_Kurd

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: Datafiles/Kurd.csv
%
% Auto-generated by MATLAB on 28-May-2020 18:53:08

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Kurd"];
opts.SelectedVariableNames = "Kurd";
opts.VariableTypes = ["string", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Var1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var1", "EmptyFieldRule", "auto");

% Import the data
tbl = readtable("Datafiles/Kurd.csv", opts);

%% Convert to output type
Kurd = tbl.Kurd;
