function [Election2004, Election2009, Election2014] = import_election

%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Elections.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2019/10/09 14:17:15

%% Import the data for 2004 elsections
[~, ~, raw] = xlsread('Datafiles/Elections.xlsx','Sheet1');
raw = raw(2:82,4:34);

%%% Replace non-numeric cells with 0.0
R = cellfun(@(x) (~isnumeric(x) && ~islogical(x)) || isnan(x),raw); % Find non-numeric cells
raw(R) = {0.0}; % Replace non-numeric cells

%%% Create output variable
Election2004 = reshape([raw{:}],size(raw));

%%% Clear temporary variables
clearvars R;

%% Import the data for 2009 elsections
[~, ~, raw] = xlsread('Datafiles/Elections.xlsx','Sheet1');
raw = raw(164:244,4:34);

%%% Replace non-numeric cells with 0.0
R = cellfun(@(x) (~isnumeric(x) && ~islogical(x)) || isnan(x),raw); % Find non-numeric cells
raw(R) = {0.0}; % Replace non-numeric cells

%%% Create output variable
Election2009 = reshape([raw{:}],size(raw));

%%% Clear temporary variables
clearvars raw R;

%% Import the data for 2014 elsections
[~, ~, raw] = xlsread('Datafiles/Elections.xlsx','Sheet1');
raw = raw(569:649,4:34);

%%% Replace non-numeric cells with 0.0
R = cellfun(@(x) (~isnumeric(x) && ~islogical(x)) || isnan(x),raw); % Find non-numeric cells
raw(R) = {0.0}; % Replace non-numeric cells

%%% Create output variable
Election2014 = reshape([raw{:}],size(raw));

%%% Clear temporary variables
clearvars raw R;



