function [Population, Population_years] = import_population

%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Population.xlsx
%    Worksheet: Sheet0
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2019/10/09 14:02:42

%% Import the data
[~, ~, raw] = xlsread('Datafiles/Population.xlsx','Sheet0');
raw = raw(2:end-1,3:end);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
Population = reshape([raw{:}],size(raw));

%% Clear temporary variables
clearvars raw R;

Population = reshape(sum(Population, 2), 81, 11);
Population_years = 2008:2018;
